# Default values for argocd-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""


argoWorkflows:
  enabled: false
certManager:
  enabled: false
externalSecrets:
  enabled: false
kubeStateMetrics:
  enabled: false
metricsServer:
  enabled: false
minioOperator:
  enabled: false
velero:
  enabled: false
