{{- if .Values.argoWorkflows.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  project: argo-master
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: "0.2.*"
    helm:
      releaseName: cluster
      version: v3
      values: |
{{ .Files.Get "files/argo-workflows.yaml" | indent 8 }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}