{{- if .Values.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: argo-master
  source:
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    chart: kubernetes-external-secrets
    targetRevision: "8.1.*"
    helm:
      releaseName: cluster
      version: v3
      values: |
{{ .Files.Get "files/external-secrets.yaml" | indent 8 }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}